// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYxhvexev_q8rVIcqiQDM6nnBdc3eZ6-0',
    appId: '1:570674157033:web:9546c17014d0856b162778',
    messagingSenderId: '570674157033',
    projectId: 'mindbloom-d0608',
    authDomain: 'mindbloom-d0608.firebaseapp.com',
    storageBucket: 'mindbloom-d0608.firebasestorage.app',
    measurementId: 'G-G1VCSKNTV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsbg0Drl2I-Gjb-Ty6W3f-Q42JfFz1yu8',
    appId: '1:570674157033:android:a03672aba0e672ef162778',
    messagingSenderId: '570674157033',
    projectId: 'mindbloom-d0608',
    storageBucket: 'mindbloom-d0608.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaaxvvxiDbb9q9-ansoOXCyhoeyAuFvQU',
    appId: '1:570674157033:ios:20be4fe46dea9167162778',
    messagingSenderId: '570674157033',
    projectId: 'mindbloom-d0608',
    storageBucket: 'mindbloom-d0608.firebasestorage.app',
    iosBundleId: 'com.aryalsadi.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaaxvvxiDbb9q9-ansoOXCyhoeyAuFvQU',
    appId: '1:570674157033:ios:20be4fe46dea9167162778',
    messagingSenderId: '570674157033',
    projectId: 'mindbloom-d0608',
    storageBucket: 'mindbloom-d0608.firebasestorage.app',
    iosBundleId: 'com.aryalsadi.moodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYxhvexev_q8rVIcqiQDM6nnBdc3eZ6-0',
    appId: '1:570674157033:web:8afd0aafe04da3e1162778',
    messagingSenderId: '570674157033',
    projectId: 'mindbloom-d0608',
    authDomain: 'mindbloom-d0608.firebaseapp.com',
    storageBucket: 'mindbloom-d0608.firebasestorage.app',
    measurementId: 'G-S9VWSJF4H9',
  );
}
